# Generated by Django 3.1.3 on 2020-12-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(max_length=200,
                                           verbose_name='Название места')),
                ('description_short', models.CharField(
                    max_length=200,
                    verbose_name='Короткое описание')),
                ('description_long',
                 models.TextField(verbose_name='Длинное описание')),
                ('lat', models.FloatField(max_length=200,
                                          verbose_name='Ширина')),
                ('lon', models.FloatField(max_length=200,
                                          verbose_name='Долгота')),
            ],
        ),
    ]
