# Generated by Django 3.1.3 on 2021-01-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='details_url',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес для скачивания доп.сведений о локации'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Уникальный идентификатор локации'),
        ),
    ]
