# Generated by Django 3.1.3 on 2021-01-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210111_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=300, verbose_name='Короткое описание'),
        ),
    ]
