# Generated by Django 3.1.3 on 2021-01-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210113_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='my_order',
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер картинки для сортировки'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Уникальный идентификатор локации'),
        ),
    ]
