# Generated by Django 3.1.3 on 2021-01-21 11:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20210120_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_id',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='image',
            name='picture_number',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description_long',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description_short',
        ),
        migrations.AddField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Длинное описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер картинки'),
        ),
    ]
