# Generated by Django 3.1.3 on 2021-01-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20210121_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Короткое описание'),
        ),
    ]
