# Generated by Django 3.1.3 on 2021-01-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20210121_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='picture_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер картинки по порядку'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
    ]
