# Generated by Django 3.1.3 on 2021-01-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20210124_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='picture_number',
        ),
    ]
