# Generated by Django 3.1.3 on 2021-01-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20210128_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Уникальный идентификатор локации'),
        ),
    ]
